# -*- coding: utf-8 -*-
"""aula8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGfNYgTSvwAHzeRVSKsOvNkVKqGNwFNB
"""

###Hábitos de estudos

print("Responda às perguntas digitando a quantidade de pontos da sua escolha (2, 1 ou 0):\n")

# Pergunta 1
print("1. Você costuma estudar com horário definido?")
print("[2] Sempre")
print("[1] Às vezes")
print("[0] Nunca")
resposta_1 = int(input("Sua resposta (digite os pontos): "))

# Pergunta 2
print("\n2. Quando recebe uma atividade, você:")
print("[2] Começa logo")
print("[1] Deixa para depois, mas faz")
print("[0] Só lembra no último momento")
resposta_2 = int(input("Sua resposta (digite os pontos): "))

# Pergunta 3
print("\n3. Você anota prazos e compromissos?")
print("[2] Sim, sempre")
print("[1] Às vezes")
print("[0] Não")
resposta_3 = int(input("Sua resposta (digite os pontos): "))

# Pergunta 4
print("\n4. Durante os estudos, você se distrai com facilidade?")
print("[2] Raramente")
print("[1] Às vezes")
print("[0] Frequentemente")
resposta_4 = int(input("Sua resposta (digite os pontos): "))

# Cálculo da pontuação total usando apenas expressões matemáticas
pontuacao_total = resposta_1 + resposta_2 + resposta_3 + resposta_4

# Exibição do resultado e da tabela
print("\n" + "="*40)
print("PONTUAÇÃO TOTAL:", pontuacao_total, "pontos")
print("="*40)

print("\n--- TABELA DE CLASSIFICAÇÃO FINAL ---")
print("7 a 8 pontos -> Perfil muito organizado")
print("4 a 6 pontos -> Perfil moderadamente organizado")
print("0 a 3 pontos -> Perfil pouco organizado")
print("========================================")