# -*- coding: utf-8 -*-
"""aula6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kru_txmhuVoPlQBz7WAqMqEoKTY0Mhkt
"""

###Calculadora de IMC

def calcular_imc(peso, altura):
    """Calcula o IMC dividindo o peso pela altura ao quadrado."""
    imc = peso / (altura ** 2)
    return imc

def classificar_imc(imc):
    """Classifica o IMC de acordo com a tabela padrão."""
    if imc <= 18.5:
        return "Abaixo do peso"
    elif imc < 25.0:
        return "Saudável"
    elif imc < 30.0:
        return "Sobrepeso"
    elif imc < 35.0:
        return "Obesidade Grau I (leve)"
    elif imc < 40.0:
        return "Obesidade Grau II (severa)"
    else:
        return "Obesidade Grau III (mórbida)"

print("=== CALCULADORA DE IMC ===")

try:
    peso_input = float(input("Digite o seu peso em kg (ex: 70.5): "))
    altura_input = float(input("Digite a sua altura em metros (ex: 1.75): "))
    meu_imc = calcular_imc(peso_input, altura_input)
    classificacao = classificar_imc(meu_imc)

    print("-" * 30)
    print(f"Seu IMC é: {meu_imc:.2f}")
    print(f"Classificação: {classificacao}")
except ValueError:
    print("Entrada inválida. Por favor, digite números para peso e altura.")
except Exception as e:
    print(f"Ocorreu um erro: {e}")