# -*- coding: utf-8 -*-
"""aula7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpUBXLjtYY74SWM1_UrFZ5kRYI4TMebN
"""

###Valor da mesada (com programa de computador)

import random

# Três filhos
filhos = ["Huguinho", "Zezinho", "Luizinho"]

# Valores possíveis da mesada
valores_possiveis = [20.00, 40.00, 60.00, 80.00, 100.00]

print("SORTEIO DA MESADA")

for filho in filhos:
    mesada_sorteada = random.choice(valores_possiveis)

    valor_formatado = f"{mesada_sorteada:.2f}".replace('.', ',')
    print(f"A mesada de {filho} este mês será de: R$ {valor_formatado}")

print("\nBoa sorte para eles no mês que vem!")