# -*- coding: utf-8 -*-
"""semana3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184fr1cPprcCvhGUOgTNP0RL6mSrj4Q9F
"""

### Calcular a área de cada ambiente do imóvel

comprimento = float(input("Digite o comprimento do imóvel:" ))
largura = float(input("Digite a largura do imóvel:" ))
area = comprimento * largura
print("A área do imóvel em (m²) é:", area)

### Eu quero uma casa no campo

def calcular_arame():
    print("Calculadora de Arame da Fazenda da Dona Dalva")

    try:
        # Recebe as dimensões da fazenda
        comprimento = float(input("Digite o comprimento da fazenda (em metros): "))
        largura = float(input("Digite a largura da fazenda (em metros): "))

        # Calcula o perímetro (soma dos 4 lados do retângulo)
        perimetro = 2 * (comprimento + largura)

        # Calcula a quantidade total de arame (5 fios)
        total_arame = perimetro * 5

        # Exibe os resultados
        print("\n--- Resultado ---")
        print(f"O perímetro total da fazenda é: {perimetro:.2f} metros.")
        print(f"A Dona Dalva precisará comprar: {total_arame:.2f} metros de arame farpado.")

    except ValueError:
        print("Por favor, digite apenas números válidos para as dimensões.")

# Executa o programa
calcular_arame()

### Aplicações práticas para a função log(.)

import math

def calcular_tempo_juros_compostos(montante, capital, taxa_juros_percentual):
    """
    Calcula o tempo necessário para um capital atingir um montante
    específico sob regime de juros compostos.
    """
    # Converte a taxa de juros de porcentagem para decimal (ex: 0.25% vira 0.0025)
    i = taxa_juros_percentual / 100

    # Aplica a fórmula derivada com logaritmos
    # math.log() calcula o logaritmo natural (base e), mas qualquer base funcionaria aqui
    tempo = math.log(montante / capital) / math.log(1 + i)

    return tempo

# --- Resolução do seu problema específico ---

# Valores dados
capital_inicial = 500.00
montante_desejado = 1500.00
taxa_mensal = 0.25 # em porcentagem

# Chamando a função
meses_necessarios = calcular_tempo_juros_compostos(montante_desejado, capital_inicial, taxa_mensal)
anos_necessarios = meses_necessarios / 12

# Exibindo os resultados
print("-" * 40)
print(f"Capital Inicial: R$ {capital_inicial:.2f}")
print(f"Montante Alvo: R$ {montante_desejado:.2f}")
print(f"Taxa de Juros: {taxa_mensal}% ao mês")
print("-" * 40)
print(f"Tempo necessário: {meses_necessarios:.2f} meses")
print(f"Isso equivale a aproximadamente {anos_necessarios:.2f} anos.")
print("-" * 40)

### Aplicações práticas para a função log(.)

import math
import matplotlib.pyplot as plt

# 1. Dados do problema
C = 500.00      # Capital inicial
M = 1500.00     # Montante desejado
i = 0.0025      # Taxa de juros (0,25% em decimal)

# 2. Aplicando a exata fórmula que você deduziu: t = log(M / C) / log(1 + i)
t = math.log(M / C) / math.log(1 + i)

print("-" * 40)
print(f"Resultado do Cálculo:")
print(f"Tempo exato: {t:.2f} meses")
print(f"Em anos: {t / 12:.2f} anos")
print("-" * 40)

# 3. Gerando os dados para o Gráfico
# Criamos uma lista de meses de 0 até o mês final calculado (arredondado para cima)
meses_lista = list(range(int(t) + 2))

# Calculamos o montante para cada mês da lista
evolucao_montante = [C * ((1 + i) ** mes) for mes in meses_lista]

# 4. Configurando e exibindo o Gráfico
plt.figure(figsize=(10, 6))
plt.plot(meses_lista, evolucao_montante, color='blue', linewidth=2, label='Crescimento do Capital')

# Linhas de marcação para o alvo
plt.axhline(y=M, color='red', linestyle='--', label=f'Montante Alvo (R$ {M:.2f})')
plt.axvline(x=t, color='green', linestyle='--', label=f'Tempo Necessário ({t:.0f} meses)')

# Títulos e legendas
plt.title('Evolução do Montante - Juros Compostos (0,25% a.m.)')
plt.xlabel('Tempo (Meses)')
plt.ylabel('Montante (R$)')
plt.legend()
plt.grid(True)

# Mostra o gráfico na tela
plt.show()

### Crescimento populacional

import math
import matplotlib.pyplot as plt

# 1. Dados do problema
taxa = 0.03        # Taxa de crescimento de 3% ao ano
multiplicador = 2  # Queremos descobrir quando a população dobra (Pt = 2 * P0)

# População do ano base (P0).
# Escolhi 1000 como exemplo para podermos visualizar no gráfico.
P0 = 1000

# 2. A fórmula exata isolando o tempo (t) com logaritmos
t = math.log(multiplicador) / math.log(1 + taxa)

# Exibindo o resultado no terminal
print("-" * 40)
print("CÁLCULO DE CRESCIMENTO POPULACIONAL")
print("-" * 40)
print(f"Taxa de crescimento: {taxa * 100}% ao ano")
print(f"Tempo exato para DOBRAR a população: {t:.2f} anos")
print("-" * 40)

# 3. Gerando os dados para o Gráfico
# Cria uma lista de anos do ano 0 até o ano final calculado
anos_lista = list(range(int(t) + 2))

# Calcula a população para cada ano usando a fórmula: Pt = P0 * (1.03)^t
evolucao_populacao = [P0 * ((1 + taxa) ** ano) for ano in anos_lista]

# 4. Configurando e exibindo o Gráfico
plt.figure(figsize=(10, 6))
plt.plot(anos_lista, evolucao_populacao, color='purple', linewidth=2, label='Curva de Crescimento')

# Linhas de marcação para o momento em que a população dobra
populacao_dobrada = P0 * multiplicador
plt.axhline(y=populacao_dobrada, color='red', linestyle='--', label=f'População Dobrada ({populacao_dobrada} hab.)')
plt.axvline(x=t, color='green', linestyle='--', label=f'Tempo Necessário ({t:.1f} anos)')

# Detalhes visuais do gráfico
plt.title('Evolução do Crescimento Populacional (3% a.a.)')
plt.xlabel('Tempo (Anos)')
plt.ylabel('Número de Habitantes (Exemplo)')
plt.legend()
plt.grid(True)

# Mostra o gráfico na tela
plt.show()

import math

def calcular_tempo_crescimento():
    print("=" * 50)
    print("   CALCULADORA UNIVERSAL DE CRESCIMENTO EXPONENCIAL")
    print("=" * 50)

    # 1. Coletando os dados do usuário
    p0 = float(input("Digite a população inicial (Ex: 1000): "))
    pt = float(input("Digite a população alvo (Ex: 2000 para dobrar): "))
    taxa_percentual = float(input("Digite a taxa de crescimento anual em % (Ex: 3): "))

    # 2. Convertendo a taxa para decimal
    i = taxa_percentual / 100

    # 3. Aplicando a fórmula generalizada com logaritmo
    t = math.log(pt / p0) / math.log(1 + i)

    # 4. Exibindo o resultado final
    print("-" * 50)
    print(f"População Inicial: {p0:.0f} habitantes")
    print(f"População Alvo:    {pt:.0f} habitantes")
    print(f"Taxa de Crescimento: {taxa_percentual}% ao ano")
    print("-" * 50)
    print(f"TEMPO NECESSÁRIO: {t:.2f} anos")
    print("=" * 50)

# Rodando o programa
calcular_tempo_crescimento()

### Calcular a área a ser pintada em cada ambiente do imóvel

comprimento = float(input("Digite o comprimento da área 1:" ))
largura = float(input("Digite a largura do imóvel:" ))
altura = float(input("Digite a altura do imóvel:" ))
area1 = comprimento * largura

comprimento = float(input("Digite o comprimento da área 2:" ))
largura = float(input("Digite a largura do imóvel:" ))
altura = float(input("Digite a altura do imóvel:" ))
area2 = comprimento * largura

comprimento = float(input("Digite o comprimento da área 3:" ))
largura = float(input("Digite a largura do imóvel:" ))
altura = float(input("Digite a altura do imóvel:" ))
area3 = comprimento * largura

area_total = area1 + 2 * area2 + 2 * area3
print("A área total a ser pintada é:", area_total)

### Projeto "Minha Mansão, Minha Vida"

comprimento = float(input("Digite o comprimento da área 1: " ))
largura = float(input("Digite a largura da área 1: " ))
altura = float(input("Digite a altura do área 1: " ))
area1 = comprimento * largura

comprimento = float(input("Digite o comprimento da área 2:" ))
largura = float(input("Digite a largura da área 2: " ))
altura = float(input("Digite a altura do área 2: " ))
area2 = comprimento * largura

comprimento = float(input("Digite o comprimento da área 3:" ))
largura = float(input("Digite a largura do área 3: " ))
altura = float(input("Digite a altura do área 3: " ))
area3 = comprimento * largura

area_total = area1 + 2 * area2 + 2 * area3
print("A área total a ser pintada é:", area_total)

### Calcular e exibir a área do seu terreno

area = area_total/2
print("A área do terreno é:", area)

### Eu quero uma casa no campo

comprimento = float(input("Digite o comprimento da fazenda: " ))
largura = float(input("Digite a largura da fazenda: " ))
area = comprimento * largura

perimetro = area
print("O perímetro da fazenda é:", perimetro)

### Quantidade de arames para cercar toda a área da fazenda